framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        # stream_options:
        #    ssl:
        #        allow_self_signed: true
        #        verify_peer: false

    # mailer:
        #transports:
            #main:
                #dsn: "smtp://smtp.gmail.com:587?encryption=tls&auth_mode=login&username=votre-adresse-gmail@gmail.com&password=votre-mot-de-passe"
                # ou :
                # host: 'smtp.gmail.com'
                # port: 587
                # encryption: tls
                # username: 'votre-adresse-gmail@gmail.com'
                # password: 'votre-mot-de-passe'